import { StyleSheet, Platform } from "react-native";
import { Colors } from "../constants/Colors";


export const styles = StyleSheet.create({
  container: {
      flex: 1,
      backgroundColor: '#f9f7f0',
    },
    masthead: {
      padding: 16,
      backgroundColor: '#f5f5f5',
      borderBottomWidth: 2,
      borderBottomColor: '#000',
      alignItems: 'center',
    },
    newspaperName: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 26,
      fontWeight: 'bold',
      textTransform: 'uppercase',
      textAlign: 'center',
    },
    divider: {
      height: 2,
      backgroundColor: '#000',
      width: '100%',
      marginVertical: 6,
    },
    tagline: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 12,
      fontStyle: 'italic',
      textAlign: 'center',
    },
    editionInfo: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      marginTop: 8,
    },
    editionDate: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 12,
    },
    editionVolume: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 12,
    },
    articleHeader: {
      padding: 16,
    },
    categoryContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    categoryTag: {
      backgroundColor: Colors.primary,
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 4,
      marginRight: 8,
    },
    categoryText: {
      color: 'white',
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 12,
      fontWeight: 'bold',
    },
    solvedBadge: {
      backgroundColor: '#4CAF50',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    solvedText: {
      color: 'white',
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 12,
      fontWeight: 'bold',
      marginLeft: 4,
    },
    headline: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 8,
      lineHeight: 30,
    },
    byline: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    bylineText: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 14,
      fontStyle: 'italic',
    },
    authorName: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 14,
      fontWeight: 'bold',
    },
    bylineDate: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 14,
      color: '#666',
    },
    imageContainer: {
      margin: 16,
      marginTop: 0,
      borderWidth: 1,
      borderColor: '#ddd',
      overflow: 'hidden',
    },
    leadImage: {
      width: '100%',
      height: 220,
      backgroundColor: '#f0f0f0',
    },
    imageCaption: {
      padding: 8,
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 12,
      fontStyle: 'italic',
      textAlign: 'center',
      backgroundColor: '#f5f5f5',
    },
    articleBody: {
      padding: 16,
    },
    dropCap: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 36,
      fontWeight: 'bold',
      lineHeight: 36,
    },
    leadParagraph: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 16,
      lineHeight: 24,
    },
    bodyText: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 16,
      lineHeight: 24,
      marginTop: 12,
    },
    infoBox: {
      margin: 16,
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 4,
      overflow: 'hidden',
    },
    infoBoxHeader: {
      backgroundColor: Colors.primary,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
    },
    infoBoxTitle: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      color: 'white',
      fontSize: 14,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    infoBoxContent: {
      padding: 12,
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 14,
      lineHeight: 20,
    },
    infoBoxButton: {
      backgroundColor: Colors.primary,
      padding: 12,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
    },
    infoBoxButtonText: {
      color: 'white',
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontWeight: 'bold',
      fontSize: 14,
      marginLeft: 8,
    },
    solutionBox: {
      margin: 16,
      marginTop: 0,
      borderWidth: 1,
      borderColor: '#4CAF50',
      borderRadius: 4,
      overflow: 'hidden',
    },
    solutionBoxHeader: {
      backgroundColor: '#4CAF50',
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
    },
    solutionBoxTitle: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      color: 'white',
      fontSize: 14,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    solutionContent: {
      padding: 12,
    },
    solutionSubtitle: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 14,
      fontWeight: 'bold',
      marginBottom: 4,
    },
    solutionText: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 14,
      marginBottom: 12,
      lineHeight: 20,
    },
    statusContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statusIndicator: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#4CAF50',
      marginRight: 8,
    },
    solutionTimestamp: {
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontSize: 12,
      fontStyle: 'italic',
      color: '#666',
      marginTop: 8,
      textAlign: 'right',
    },
    // New compact action bar
    compactActionBar: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      padding: 12,
      borderTopWidth: 1,
      borderTopColor: '#ddd',
      backgroundColor: '#f5f5f5',
    },
    compactButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'white',
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
      borderWidth: 1,
      borderColor: Colors.primary,
      flexDirection: 'row',
    },
    compactButtonText: {
      fontSize: 12,
      color: Colors.primary,
      marginLeft: 2,
    },
    compactResolveButton: {
      height: 40,
      borderRadius: 20,
      backgroundColor: '#4CAF50',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginLeft: 8,
      justifyContent: 'center',
    },
    compactResolveText: {
      color: 'white',
      fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
      fontWeight: 'bold',
      fontSize: 12,
      marginLeft: 4,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.9)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    fullImage: {
      width: '90%',
      height: '70%',
      backgroundColor: '#000',
    },
    closeButton: {
      position: 'absolute',
      top: 40,
      right: 20,
      backgroundColor: 'rgba(0,0,0,0.5)',
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });