import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  solutionContainer: {
    backgroundColor: "#f9f7f0",
    borderWidth: 1,
    borderColor: "#4CAF50",
    borderRadius: 4,
    marginVertical: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  solutionHeader: {
    backgroundColor: "#4CAF50",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  solutionTitle: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
    marginLeft: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  solutionContent: {
    padding: 12,
    borderTopWidth: 1,
    borderTopStyle: "dotted",
    borderTopColor: "#ccc",
  },
  solutionLabel: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 8,
    marginBottom: 4,
    color: "#333",
  },
  solutionText: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 15,
    lineHeight: 22,
    color: "#333",
    marginBottom: 12,
  },
  solutionDivider: {
    height: 1,
    backgroundColor: "#ddd",
    marginVertical: 8,
  },
  solutionMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  solutionDate: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 12,
    fontStyle: "italic",
    color: "#666",
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#4CAF50",
    marginRight: 6,
  },
  statusText: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 13,
    fontWeight: "bold",
    color: "#4CAF50",
  },
  // Additional newspaper-style elements
  solutionQuote: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 15,
    fontStyle: "italic",
    lineHeight: 22,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginVertical: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#4CAF50",
    backgroundColor: "#f2f2f2",
  },
  solvedByText: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 12,
    color: "#666",
    fontStyle: "italic",
    textAlign: "right",
    marginTop: 4,
  },
  columnLayout: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 4,
  },
  columnItem: {
    width: "48%",
    marginBottom: 8,
  },
  beforeAfterLabel: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 12,
    fontWeight: "bold",
    textTransform: "uppercase",
    textAlign: "center",
    backgroundColor: "#f0f0f0",
    paddingVertical: 2,
    marginBottom: 4,
  },
  headlineStyle: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif", 
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 8,
    paddingHorizontal: 12,
    lineHeight: 22,
  },
  timestampRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#f5f5f5",
  },
  clockIcon: {
    marginRight: 4,
  },
  timeStampText: {
    fontFamily: Platform.OS === "ios" ? "Times New Roman" : "serif",
    fontSize: 11,
    fontStyle: "italic",
    color: "#777",
  }
});